Primeiro passo - instalação das bibliotecas pandas-datareader, yfinance, numpy e matplotlib

In [ ]:
!pip install pandas-datareader yfinance numpy matplotlib

In [ ]:
import pandas as pd
import pandas_datareader.data as pdr
import yfinance

In [ ]:
yfinance.pdr_override()

yfinance: pandas_datareader support is deprecated & semi-broken so will be removed in a future verison. Just use yfinance.


In [ ]:
data_inicial = '2023-07-01'
data_final = '2023-12-01'

df_cotacoes = pdr.get_data_yahoo('PETR3.SA', data_inicial, data_final)
display(df_cotacoes)

[*********************100%%**********************]  1 of 1 completed


Open       High        Low      Close  Adj Close    Volume
Date                                                                       
2023-07-03  33.410000  33.840000  33.400002  33.669998  29.368717  10255400
2023-07-04  33.660000  34.029999  33.529999  33.750000  29.438501   3080800
2023-07-05  33.720001  34.160000  33.320000  33.740002  29.429781  14131000
2023-07-06  33.480000  33.700001  32.930000  33.310001  29.054710  12623600
2023-07-07  33.459999  33.869999  33.070000  33.130001  28.897705   8279200
...               ...        ...        ...        ...        ...       ...
2023-11-24  37.700001  38.509998  37.340000  37.750000  35.315979  11929600
2023-11-27  37.520000  37.860001  37.009998  37.500000  35.082096   9476000
2023-11-28  37.500000  38.090000  37.500000  37.849998  35.409527   7718000
2023-11-29  38.150002  38.290001  37.150002  37.349998  34.941769   8632000
2023-11-30  37.560001  38.209999  37.169998  37.700001  35.269203  15990200

[105 rows x 6 columns]

In [ ]:
df_cotacoes

Open       High        Low      Close  Adj Close    Volume
Date                                                                       
2023-07-03  33.410000  33.840000  33.400002  33.669998  29.368717  10255400
2023-07-04  33.660000  34.029999  33.529999  33.750000  29.438501   3080800
2023-07-05  33.720001  34.160000  33.320000  33.740002  29.429781  14131000
2023-07-06  33.480000  33.700001  32.930000  33.310001  29.054710  12623600
2023-07-07  33.459999  33.869999  33.070000  33.130001  28.897705   8279200
...               ...        ...        ...        ...        ...       ...
2023-11-24  37.700001  38.509998  37.340000  37.750000  35.315979  11929600
2023-11-27  37.520000  37.860001  37.009998  37.500000  35.082096   9476000
2023-11-28  37.500000  38.090000  37.500000  37.849998  35.409527   7718000
2023-11-29  38.150002  38.290001  37.150002  37.349998  34.941769   8632000
2023-11-30  37.560001  38.209999  37.169998  37.700001  35.269203  15990200

[105 rows x 6 columns]

Previsão da ação

In [ ]:
#importando as bibliotecas
from sklearn.feature_selection import SelectKBest
from sklearn.model_selection import GridSearchCV
from sklearn.neural_network import MLPRegressor
from sklearn.preprocessing import MinMaxScaler
from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error, r2_score
import matplotlib.pyplot as plt



In [ ]:
#criando novos campos de médias moveis
df_cotacoes['media5d']= df_cotacoes['Adj Close'].rolling(5).mean()


In [ ]:
df_cotacoes

Open       High        Low      Close  Adj Close    Volume  \
Date                                                                          
2023-07-03  33.410000  33.840000  33.400002  33.669998  29.368717  10255400   
2023-07-04  33.660000  34.029999  33.529999  33.750000  29.438501   3080800   
2023-07-05  33.720001  34.160000  33.320000  33.740002  29.429781  14131000   
2023-07-06  33.480000  33.700001  32.930000  33.310001  29.054710  12623600   
2023-07-07  33.459999  33.869999  33.070000  33.130001  28.897705   8279200   
...               ...        ...        ...        ...        ...       ...   
2023-11-24  37.700001  38.509998  37.340000  37.750000  35.315979  11929600   
2023-11-27  37.520000  37.860001  37.009998  37.500000  35.082096   9476000   
2023-11-28  37.500000  38.090000  37.500000  37.849998  35.409527   7718000   
2023-11-29  38.150002  38.290001  37.150002  37.349998  34.941769   8632000   
2023-11-30  37.560001  38.209999  37.169998  37.700001  35.269203  15990200   

              media5d  
Date                   
2023-07-03        NaN  
2023-07-04        NaN  
2023-07-05        NaN  
2023-07-06        NaN  
2023-07-07  29.237883  
...               ...  
2023-11-24  35.350367  
2023-11-27  35.255871  
2023-11-28  35.297266  
2023-11-29  35.233651  
2023-11-30  35.203715  

[105 rows x 7 columns]

In [ ]:
#Ajustando o fechamento um dia para frente
df_cotacoes['Adj Close']= df_cotacoes['Adj Close'].shift(-1)
df_cotacoes.head(10)

Open       High        Low      Close  Adj Close    Volume  \
Date                                                                          
2023-07-03  33.410000  33.840000  33.400002  33.669998  29.438501  10255400   
2023-07-04  33.660000  34.029999  33.529999  33.750000  29.429781   3080800   
2023-07-05  33.720001  34.160000  33.320000  33.740002  29.054710  14131000   
2023-07-06  33.480000  33.700001  32.930000  33.310001  28.897705  12623600   
2023-07-07  33.459999  33.869999  33.070000  33.130001  28.897705   8279200   
2023-07-10  32.840000  33.430000  32.779999  33.130001  28.670919   6997700   
2023-07-11  33.080002  33.270000  32.750000  32.869999  28.583694   9533900   
2023-07-12  32.869999  33.540001  32.750000  32.770000  29.002375  12229800   
2023-07-13  32.799999  33.380001  32.779999  33.250000  28.391796   9831700   
2023-07-14  33.029999  33.189999  32.419998  32.549999  28.400522  13967700   

              media5d  
Date                   
2023-07-03        NaN  
2023-07-04        NaN  
2023-07-05        NaN  
2023-07-06        NaN  
2023-07-07  29.237883  
2023-07-10  29.143681  
2023-07-11  28.990164  
2023-07-12  28.820947  
2023-07-13  28.810480  
2023-07-14  28.709298

In [ ]:
#retirando todos os dados nulos
df_cotacoes.dropna(inplace=True)
df_cotacoes

Open       High        Low      Close  Adj Close    Volume  \
Date                                                                          
2023-07-07  33.459999  33.869999  33.070000  33.130001  28.897705   8279200   
2023-07-10  32.840000  33.430000  32.779999  33.130001  28.670919   6997700   
2023-07-11  33.080002  33.270000  32.750000  32.869999  28.583694   9533900   
2023-07-12  32.869999  33.540001  32.750000  32.770000  29.002375  12229800   
2023-07-13  32.799999  33.380001  32.779999  33.250000  28.391796   9831700   
...               ...        ...        ...        ...        ...       ...   
2023-11-23  37.689999  37.860001  37.389999  37.860001  35.315979   2804600   
2023-11-24  37.700001  38.509998  37.340000  37.750000  35.082096  11929600   
2023-11-27  37.520000  37.860001  37.009998  37.500000  35.409527   9476000   
2023-11-28  37.500000  38.090000  37.500000  37.849998  34.941769   7718000   
2023-11-29  38.150002  38.290001  37.150002  37.349998  35.269203   8632000   

              media5d  
Date                   
2023-07-07  29.237883  
2023-07-10  29.143681  
2023-07-11  28.990164  
2023-07-12  28.820947  
2023-07-13  28.810480  
...               ...  
2023-11-23  35.421554  
2023-11-24  35.350367  
2023-11-27  35.255871  
2023-11-28  35.297266  
2023-11-29  35.233651  

[100 rows x 7 columns]

In [ ]:
#Verificando quantidade de linhas
qtd_linhas = len(df_cotacoes)
print(qtd_linhas)
#70% treinamento
qtd_linha_treino = qtd_linhas - 30
#20% teste
qtd_linha_teste = qtd_linhas - 10
#10% validação
qtd_linha_validacao = qtd_linha_treino - qtd_linha_teste

info = {
    f"linhas treino: {qtd_linha_treino} "
    f"linhas teste: {qtd_linha_treino}:{qtd_linha_teste} "
    f"linhas validacao: {qtd_linha_teste}:{qtd_linhas} "
}

info



100


{'linhas treino: 70 linhas teste: 70:90 linhas validacao: 90:100 '}

In [ ]:
#reindexando
# df_cotacoes = df_cotacoes.reset_index(inplace=True)
df_cotacoes = df_cotacoes.reset_index(drop=True)
print(df_cotacoes)

         Open       High        Low      Close  Adj Close    Volume    media5d
0   33.459999  33.869999  33.070000  33.130001  28.897705   8279200  29.237883
1   32.840000  33.430000  32.779999  33.130001  28.670919   6997700  29.143681
2   33.080002  33.270000  32.750000  32.869999  28.583694   9533900  28.990164
3   32.869999  33.540001  32.750000  32.770000  29.002375  12229800  28.820947
4   32.799999  33.380001  32.779999  33.250000  28.391796   9831700  28.810480
..        ...        ...        ...        ...        ...       ...        ...
95  37.689999  37.860001  37.389999  37.860001  35.315979   2804600  35.421554
96  37.700001  38.509998  37.340000  37.750000  35.082096  11929600  35.350367
97  37.520000  37.860001  37.009998  37.500000  35.409527   9476000  35.255871
98  37.500000  38.090000  37.500000  37.849998  34.941769   7718000  35.297266
99  38.150002  38.290001  37.150002  37.349998  35.269203   8632000  35.233651

[100 rows x 7 columns]


In [ ]:
#Separação de features e labels
features = df_cotacoes.drop(['Adj Close'], axis=1)
label = df_cotacoes['Adj Close']

In [ ]:
#Escolhendo as melhores features
feature_list = ('Open','High','Low', 'Close','Volume',	'media5d')

k_best_features = SelectKBest(k= 'all')
k_best_features.fit_transform(features,label)
k_best_features_score = k_best_features.scores_
raw_pairs = zip(feature_list[1:], k_best_features_score)
ordered_pairs = list(reversed(sorted(raw_pairs, key= lambda x: x[1])))

k_best_features_final = dict(ordered_pairs[:15])
best_features = k_best_features_final.keys()
print('Melhores features:')
print(k_best_features_final)

Melhores features:
{'High': 307.5000679739848, 'Close': 200.89334857067618, 'Volume': 51.53002421025359, 'Low': 37.3698296969006, 'media5d': 0.7506403954335604}


In [ ]:
#Separando as melhores features
features = df_cotacoes.drop(['Low', 'media5d'], axis=1)

In [ ]:
#Normalizando os dados de entrada (features)
#Gerando o novo padrão
scaler = MinMaxScaler().fit(features)
features_scale = scaler.transform(features)

print('features:', features_scale.shape)
print(features_scale)





features: (100, 5)
[[0.15176707 0.13714905 0.09159505 0.07923668 0.14794137]
 [0.08731811 0.08963301 0.09159505 0.05499966 0.1133111 ]
 [0.11226632 0.07235441 0.06357758 0.04567775 0.18184742]
 [0.09043649 0.10151212 0.05280189 0.09042293 0.25469934]
 [0.08316001 0.08423352 0.10452596 0.0251692  0.18989493]
 [0.10706849 0.0637149  0.02909487 0.02610178 0.30166301]
 [0.         0.0086395  0.03017268 0.         0.29921741]
 [0.05301438 0.01943847 0.         0.01677967 0.15202188]
 [0.01559268 0.         0.01939658 0.04008412 0.22517646]
 [0.04781696 0.02699783 0.04633623 0.09601615 0.2586123 ]
 [0.08627879 0.09611263 0.11099163 0.1603371  0.36955617]
 [0.14553032 0.15550779 0.18534491 0.2172013  0.30232238]
 [0.25987529 0.22462218 0.25107771 0.20321793 0.18304455]
 [0.26507272 0.23218154 0.23491376 0.02237289 0.35104796]
 [0.21829508 0.17062651 0.02586224 0.07364326 0.35943597]
 [0.07276516 0.06263517 0.08512939 0.2358451  0.14039108]
 [0.15592517 0.24082104 0.27262951 0.16779507 0.39733

In [ ]:
#Separação dos dados treinamento, teste e validação
x_train = features_scale[:qtd_linha_treino]
x_test = features_scale[qtd_linha_treino:qtd_linha_teste]

y_train = label[:qtd_linha_treino]
y_test = label[qtd_linha_treino:qtd_linha_teste]


In [ ]:
#Treinamento com regressão linear
lr = linear_model.LinearRegression()
lr.fit(x_train, y_train)
pred = lr.predict(x_test)
cd= r2_score(y_test, pred)

f"Coeficiente de determinação :  {cd * 100: .2f}"


'Coeficiente de determinação :   100.00'

In [ ]:
#Executando a previsão
previsao = features_scale[qtd_linha_teste:qtd_linhas]

res_full = df_cotacoes['Adj Close']
res = res_full[qtd_linha_teste:qtd_linhas]

pred = lr.predict(previsao)

df = pd.DataFrame({'real':res, 'previsao': pred})
df['real'] = df['real'].shift(+1)

df


real   previsao
90        NaN  35.671913
91  35.671913  35.554577
92  35.554577  35.202549
93  35.202549  35.259846
94  35.259846  35.418884
95  35.418884  35.315979
96  35.315979  35.082096
97  35.082096  35.409527
98  35.409527  34.941769
99  34.941769  35.269203